name: Format PR Title and Body

on:
  pull_request:
    types: [opened]

jobs:
  format-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR title and body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          REPO: ${{ github.repository }}
        run: |
          BRANCH_NAME="${HEAD_REF}"
          ISSUE_TITLE="$(echo "$BRANCH_NAME" | sed -E 's/^[0-9]+-//' | sed -E 's/-/ /g' | sed -E 's/\b(.)/\u\1/g')"
          NEW_TITLE="Resolves: $ISSUE_TITLE"
          NEW_BODY="Closes #$BRANCH_NAME"
          gh pr edit "$PR_NUMBER" --repo "$REPO" --title "$NEW_TITLE" --body "$NEW_BODY"