name: Summarize new issues

on:
  issues:
    types: [opened, edited]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      models: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          model: "gpt-4o"  # Remove the "openai/" prefix
          max-tokens: 300  # Increase token limit
          prompt: |
            Please provide a concise summary of this GitHub issue in one paragraph:
            
            Title: "${{ github.event.issue.title }}"
            
            Body: "${{ github.event.issue.body || 'No description provided.' }}"
            
            Focus on the main problem, requested feature, or question being raised.

      - name: Comment with AI summary
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 AI Summary\n\n${{ steps.inference.outputs.response }}`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}